//! silent_profile.rs — footage profiles proven on REAL silent footage
//! (silent-screen profile regression, end-to-end).
//!
//! Role: runs the real python sidecar over testdata/silent_screen.mp4 (a
//! 20s silent screen-demo-like clip, generated by
//! `scripts/make-test-assets.sh --silent-only`), then asserts the check
//! battery's profile contract on the MEASURED facts:
//!   - talking_head (default) FAILS the footage on exactly the 4 by-design
//!     checks (lufs, caption_presence, black_or_frozen_frames,
//!     silence_at_edges) — the silent-screen regression case, reproduced;
//!   - auto-detect PROPOSES silent_screen_demo in the footage_profile
//!     metadata entry (proposal only, never applied);
//!   - explicit silent_screen_demo PASSES with every waiver RECORDED
//!     (waived_by_profile + measured_pass + evidence preserved).
//!
//! `#[ignore]` by default because it needs local state a bare CI checkout
//! lacks: app/perception/py/.venv installed AND the generated clip.
//! Execute explicitly:
//!     scripts/make-test-assets.sh --silent-only
//!     cargo test -p cut-perception --test silent_profile -- --ignored
//!
//! Dependencies: cut-core (project/EDL builders), sidecar venv, ffprobe.
//! Primary callers: developers and CI jobs with the required runtime.

use cut_core::{edl_from_project, Clip, MediaClip, Project, ProjectSettings};
use cut_perception::{
    run_all, run_all_with_profile, run_instruments, FootageProfile, InstrumentSet, RenderFacts,
    FOOTAGE_PROFILE_CHECK,
};
use std::path::{Path, PathBuf};

/// Repo root = CARGO_MANIFEST_DIR (app/perception) /../..
fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .unwrap()
}

/// Container duration via ffprobe (ms) — the same truth the server would
/// put into RenderFacts.duration_ms.
fn probe_duration_ms(path: &Path) -> u64 {
    let out = std::process::Command::new("ffprobe")
        .args([
            "-v",
            "error",
            "-show_entries",
            "format=duration",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
        ])
        .arg(path)
        .output()
        .expect("ffprobe runs");
    let s = String::from_utf8_lossy(&out.stdout);
    (s.trim().parse::<f64>().expect("numeric duration") * 1000.0) as u64
}

/// One media clip spanning the whole file on a track.
fn span_clip(id: &str, asset: &str, duration_ms: u64) -> Clip {
    Clip::Media(MediaClip {
        id: id.into(),
        asset: asset.into(),
        src_in_ms: 0,
        src_out_ms: duration_ms,
        effects: vec![],
        gain_db: 0.0,
        transform: None,
        crop: None,
        fade: None,
        xfade_in_ms: 0,
        xfade_kind: None,
        speed: 1.0,
        grade: None,
        matte: None,
        mask: None,
        reverse: false,
        freeze: None,
        animation: None,
        keyframes: vec![],
        eq: None,
        mute_ranges: vec![],
        stabilize: None,
        speed_ramp: None,
        input_color_space: None,
        nest: None,
        grade_stack: vec![],
        grade_windows: vec![],
    })
}

#[test]
#[ignore = "needs venv + testdata/silent_screen.mp4 (scripts/make-test-assets.sh --silent-only)"]
fn silent_screen_footage_fails_talking_head_passes_screen_demo() {
    let media = repo_root().join("testdata/silent_screen.mp4");
    assert!(
        media.exists(),
        "run scripts/make-test-assets.sh --silent-only first — {} missing",
        media.display()
    );
    let receipts = tempfile::tempdir().unwrap();

    // ---- 1. REAL instrument run over the silent clip -----------------------
    let report = run_instruments(
        &media,
        receipts.path(),
        "out",
        "sha256:silent-itest",
        InstrumentSet::Full,
        None,
    )
    .expect("full instrument run must succeed on silent footage (the non-finite peak guard)");

    // Measured signature of the clip (by construction, asserted not assumed):
    let words = report.words.as_ref().expect("words instrument ran");
    assert_eq!(
        words.words.len(),
        0,
        "silent clip must transcribe to 0 words"
    );
    assert!(!report.silences.is_empty(), "full-length silence expected");
    assert!(
        report.frozen_spans.len() >= 2,
        "static-UI spans split by the two motion bursts expected, got {:?}",
        report.frozen_spans
    );
    let loud = report.loudness.as_ref().expect("loudness measured");
    assert!(
        loud.integrated_lufs <= -50.0,
        "digital silence: {} LUFS",
        loud.integrated_lufs
    );

    // ---- 2. timeline spanning the file + facts as the server builds them ---
    let duration_ms = probe_duration_ms(&media);
    let mut p = Project::new("silent-itest", ProjectSettings::default());
    p.track_mut("v1")
        .unwrap()
        .clips
        .push(span_clip("c1", "out", duration_ms));
    p.track_mut("a1t")
        .unwrap()
        .clips
        .push(span_clip("ac1", "out", duration_ms));
    let edl = edl_from_project(&p);
    let facts = RenderFacts {
        duration_ms,
        loudness: report.loudness.clone(),
        output_report: Some(report),
    };

    // ---- 3. talking_head (default) must FAIL exactly the 4 by-design checks
    let th = run_all(&p, &edl, &[], &facts, &[]);
    let failing: Vec<&str> = th
        .iter()
        .filter(|c| !c.pass)
        .map(|c| c.name.as_str())
        .collect();
    assert_eq!(
        failing,
        vec![
            "lufs",
            "caption_presence",
            "black_or_frozen_frames",
            "silence_at_edges"
        ],
        "the silent-screen regression case must reproduce"
    );
    let meta = th
        .iter()
        .find(|c| c.name == FOOTAGE_PROFILE_CHECK)
        .expect("footage_profile metadata entry appended");
    assert_eq!(meta.details["active_profile"], "talking_head");
    assert_eq!(
        meta.details["proposed_profile"], "silent_screen_demo",
        "auto-detect must PROPOSE the screen-demo profile: {:?}",
        meta.evidence
    );

    // ---- 4. explicit silent_screen_demo must PASS with recorded waivers ----
    let sd = run_all_with_profile(
        &p,
        &edl,
        &[],
        &facts,
        &[],
        Some(FootageProfile::SilentScreenDemo),
    );
    let still_failing: Vec<&str> = sd
        .iter()
        .filter(|c| !c.pass)
        .map(|c| c.name.as_str())
        .collect();
    assert!(
        still_failing.is_empty(),
        "screen-demo profile must pass this footage, failing: {still_failing:?}"
    );
    for name in ["lufs", "caption_presence", "silence_at_edges"] {
        let c = sd.iter().find(|c| c.name == name).unwrap();
        assert_eq!(c.details["waived_by_profile"], "silent_screen_demo");
        assert_eq!(
            c.details["measured_pass"], false,
            "{name}: measured outcome preserved"
        );
    }
    let bf = sd
        .iter()
        .find(|c| c.name == "black_or_frozen_frames")
        .unwrap();
    assert_eq!(bf.details["variant"], "silent_screen_demo (UI-tuned)");
    assert!(
        !bf.evidence["waived_frozen_spans"]
            .as_array()
            .unwrap()
            .is_empty(),
        "waived frozen spans must stay in evidence for the judge layer"
    );
    assert_eq!(
        bf.details["stuck_span_count"], 0,
        "no wall-to-wall span on this clip"
    );

    // Receipt-level aggregate (RenderReceipt::compute_pass equivalent).
    assert!(
        sd.iter().all(|c| c.pass),
        "aggregate receipt pass under the right profile"
    );

    eprintln!(
        "silent_profile: talking_head failed {:?}; silent_screen_demo passed with {} waivers",
        failing,
        sd.iter()
            .filter(|c| c.details.get("waived_by_profile").is_some())
            .count()
    );
}
