import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')

const identity = read('../../app/recorder/record-capture/src/monitor_identity.rs')
const windows = read('../../app/recorder/record-capture/src/windows_monitor_target.rs')
const macos = read('../../app/recorder/record-capture/src/macos_monitor_target.rs')
const projection = read('../../app/server/src/screen_record/doctor_projection.rs')
const record = read('../src/panels/Record/index.tsx')
const schema = JSON.parse(read('../../schema/verbs.json'))
const reference = read('../../skill/shellx-cut/reference.md')
const debugApi = read('../../docs/public/DEBUG_API.md')

assert.match(identity, /shellx-monitor-v1/, 'monitor identities are versioned')
assert.match(identity, /Sha256/, 'the public id does not expose native display values')
assert.match(identity, /fn resolve_exact/, 'future target selection has one exact resolver')
assert.match(identity, /no fallback candidate/, 'resolver documentation rejects substitutes')

assert.match(windows, /monitorDevicePath/, 'Windows derives identity from the native target path')
assert.match(windows, /resolve_exact\(/, 'Windows re-enumerates and matches the exact identity')
assert.doesNotMatch(windows, /or_else\(.*primary|or_else\(.*width/i, 'Windows has no primary/geometry fallback')
assert.match(macos, /display\.display_id\(\)/, 'macOS derives identity from ScreenCaptureKit')
assert.match(macos, /resolve_exact\(/, 'macOS re-enumerates and matches the exact identity')
assert.match(projection, /id: monitor\.id/, 'Doctor projects the native id unchanged')
const windowsCapture = read('../../app/recorder/record-capture/src/windows.rs')
const macosCapture = read('../../app/recorder/record-capture/src/macos.rs')
assert.match(windowsCapture, /if let Some\(id\) = cfg\.monitor_id\.as_deref\(\)/, 'WGC prefers an explicit exact monitor identity')
assert.match(windowsCapture, /windows_monitor_target::resolve_monitor\(id\)/, 'WGC re-enumerates the exact monitor identity')
assert.match(macosCapture, /if let Some\(id\) = cfg\.monitor_id\.as_deref\(\)/, 'ScreenCaptureKit accepts the explicit exact monitor identity')
assert.match(macosCapture, /macos_monitor_target::monitor_id\(display\).*Some\(id\)/s, 'ScreenCaptureKit matches only the current opaque identity')

assert.doesNotMatch(read('../../app/recorder/record-capture/src/windows_picker.rs'), /monitor_id\(monitor\)\?/, 'a missing future id does not hide the current display row')
assert.match(record, /interface MonitorInfo \{ id\?: string; index: number;/, 'Record types the optional additive id')
assert.match(record, /const selectedMonitor = monitorIdx === null/, 'Record resolves its selected Doctor row before start')
assert.match(record, /startArgs\.monitor_id = selectedMonitor\.id/, 'Record returns the opaque monitor identity unchanged')
assert.doesNotMatch(record, /monitor_id = selectedMonitor\.(name|width|height|primary)/, 'Record never derives monitor identity from display copy')

const doctor = schema.verbs.find((candidate: { name?: string }) => candidate.name === 'screen_record.doctor')
assert.ok(doctor, 'screen_record.doctor remains public')
assert.match(doctor.result, /monitors:\[\{id\?,index,name,width,height,primary\}\]/, 'schema exposes the additive monitor id shape')
assert.match(doctor.result, /Pass that `id` unchanged as `screen_record\.start\.monitor_id`/i, 'schema owns the exact picker-to-start contract')
const start = schema.verbs.find((candidate: { name?: string }) => candidate.name === 'screen_record.start')
assert.ok(start, 'screen_record.start remains public')
assert.match(start.args.properties.monitor_id.description, /opaque exact native identity/i, 'start accepts the Doctor identity explicitly')
assert.match(start.args.properties.monitor_id.description, /no ordinal.*display-name.*primary-state.*geometry fallback/i, 'start rejects surrogate monitor selection')
assert.doesNotMatch(JSON.stringify(doctor), /screen_record\.select_region/, 'this seam does not claim a Region verb')
assert.match(reference, /Pass that `id` unchanged as `screen_record\.start\{monitor_id\}`/, 'agent reference explains exact start admission')
assert.match(debugApi, /Pass that\s+`id` unchanged as `screen_record\.start\{monitor_id\}`/i, 'public docs explain current exact monitor admission')

console.log('PASS exact native monitor identity contract')
