//! fixtures.rs — synthetic `EventTrack` generators.
//!
//! Because live screen capture cannot run headless (WSL/CI), these hand-built
//! tracks are the test inputs for the whole engine + render pipeline. They model
//! realistic demo interactions (a click walkthrough, a scroll-and-type read) so
//! the auto-zoom / cursor-polish / key-cast logic has something true-to-life to
//! chew on. A matching synthetic *video* is generated by record-render.

use crate::error::{error_codes, RecordError, Result};
use crate::event::{
    ClickSample, CursorSample, EventTrack, KeySample, Monitor, MouseButton, ScrollSample,
};

/// Generate a named fixture EventTrack.
pub fn generate(kind: &str) -> Result<EventTrack> {
    match kind {
        "click-walkthrough" => Ok(click_walkthrough()),
        "scroll-read" => Ok(scroll_read()),
        other => Err(RecordError::new(
            error_codes::INVALID_ARGS,
            format!("unknown fixture kind '{other}'"),
            "valid kinds: click-walkthrough, scroll-read",
        )
        .with_action("pass --kind click-walkthrough or --kind scroll-read")),
    }
}

/// 1920×1080, ~20s: cursor eases between 6 focus points, clicking on arrival.
/// Exercises auto-zoom (6 click anchors) and cursor smoothing.
fn click_walkthrough() -> EventTrack {
    let (w, h) = (1920u32, 1080u32);
    let points: [(f64, f64); 6] = [
        (300.0, 250.0),
        (1500.0, 300.0),
        (960.0, 540.0),
        (400.0, 850.0),
        (1600.0, 900.0),
        (960.0, 200.0),
    ];
    let dwell_ms = 700u64; // pause (and click) at each point
    let move_ms = 2000u64; // travel between points
    let step_ms = 40u64; // cursor sample period during travel

    let mut cursor = Vec::new();
    let mut clicks = Vec::new();
    let mut t = 0u64;

    cursor.push(CursorSample {
        t_ms: t,
        x: points[0].0,
        y: points[0].1,
    });

    for i in 1..points.len() {
        let (x0, y0) = points[i - 1];
        let (x1, y1) = points[i];

        // Click on the point we're currently dwelling at.
        clicks.push(ClickSample {
            t_ms: t + 50,
            x: x0,
            y: y0,
            button: MouseButton::Left,
            down: true,
        });
        clicks.push(ClickSample {
            t_ms: t + 90,
            x: x0,
            y: y0,
            button: MouseButton::Left,
            down: false,
        });

        t += dwell_ms;
        cursor.push(CursorSample {
            t_ms: t,
            x: x0,
            y: y0,
        });

        // Travel with a smoothstep ease so the raw path already looks human.
        let steps = (move_ms / step_ms).max(1);
        for s in 1..=steps {
            let f = s as f64 / steps as f64;
            let e = f * f * (3.0 - 2.0 * f); // smoothstep
            cursor.push(CursorSample {
                t_ms: t + s * step_ms,
                x: x0 + (x1 - x0) * e,
                y: y0 + (y1 - y0) * e,
            });
        }
        t += move_ms;
    }

    // Final dwell + click at the last point.
    let (xl, yl) = points[points.len() - 1];
    clicks.push(ClickSample {
        t_ms: t + 50,
        x: xl,
        y: yl,
        button: MouseButton::Left,
        down: true,
    });
    clicks.push(ClickSample {
        t_ms: t + 90,
        x: xl,
        y: yl,
        button: MouseButton::Left,
        down: false,
    });
    t += dwell_ms;
    cursor.push(CursorSample {
        t_ms: t,
        x: xl,
        y: yl,
    });

    EventTrack {
        duration_ms: t,
        screen_w: w,
        screen_h: h,
        monitors: vec![Monitor {
            id: 0,
            x: 0,
            y: 0,
            w,
            h,
            primary: true,
        }],
        cursor,
        clicks,
        scrolls: vec![],
        keys: vec![],
    }
}

/// 1920×1080, ~15s: cursor mostly still while the page scrolls, then a typed
/// search term. Exercises scroll handling, idle detection, and key-cast.
fn scroll_read() -> EventTrack {
    let (w, h) = (1920u32, 1080u32);
    let x = 960.0;
    let y = 540.0;
    let mut cursor = vec![CursorSample { t_ms: 0, x, y }];
    let mut scrolls = Vec::new();
    let mut keys = Vec::new();

    let mut t = 0u64;
    for _ in 0..15 {
        t += 800;
        scrolls.push(ScrollSample {
            t_ms: t,
            x,
            y,
            dx: 0.0,
            dy: -3.0,
        });
        cursor.push(CursorSample { t_ms: t, x, y });
    }

    // Type "shellx" near the end (key-cast source).
    let mut kt = t + 1000;
    for ch in "shellx".chars() {
        keys.push(KeySample {
            t_ms: kt,
            key: ch.to_string(),
            down: true,
        });
        keys.push(KeySample {
            t_ms: kt + 30,
            key: ch.to_string(),
            down: false,
        });
        kt += 180;
    }
    t = kt + 500;
    cursor.push(CursorSample { t_ms: t, x, y });

    EventTrack {
        duration_ms: t,
        screen_w: w,
        screen_h: h,
        monitors: vec![Monitor {
            id: 0,
            x: 0,
            y: 0,
            w,
            h,
            primary: true,
        }],
        cursor,
        clicks: vec![],
        scrolls,
        keys,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn click_walkthrough_is_well_formed() {
        let t = generate("click-walkthrough").unwrap();
        assert!(t.duration_ms > 10_000);
        assert_eq!(t.click_downs().count(), 6);
        // cursor samples strictly non-decreasing in time
        for w in t.cursor.windows(2) {
            assert!(w[1].t_ms >= w[0].t_ms);
        }
        // all cursor positions in-bounds
        for c in &t.cursor {
            assert!(c.x >= 0.0 && c.x <= t.screen_w as f64);
            assert!(c.y >= 0.0 && c.y <= t.screen_h as f64);
        }
    }

    #[test]
    fn scroll_read_has_scrolls_and_keys() {
        let t = generate("scroll-read").unwrap();
        assert_eq!(t.scrolls.len(), 15);
        assert_eq!(t.keys.iter().filter(|k| k.down).count(), 6);
    }

    #[test]
    fn unknown_kind_errors() {
        assert!(generate("nope").is_err());
    }
}
